version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/jsondiff
    environment:
      artifact_dir: "artifacts"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Build Variables
          command: |
            echo 'export BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'`' >> $BASH_ENV
      - run:
          name: Run and test jsondiff
          command: |
            ./build.sh
            docker run -d --name jsondiff -p 8080:80 polyglotted/jsondiff
            sleep 10
            curl --write-out %{http_code} --silent --output /dev/null localhost:8080
      - run:
          name: Collect Artifacts
          command: |
            mkdir -p ${artifact_dir}/docker/
            docker images > ${artifact_dir}/docker/images.txt
            docker inspect polyglotted/jsondiff > ${artifact_dir}/docker/info.txt
            docker logs jsondiff > ${artifact_dir}/docker/logs.txt
          when: always
      - store_artifacts:
          path: artifacts
      - run:
          name: Cleanup
          command: docker rm -f jsondiff

  deploy:
    docker:
      - image: circleci/golang
    working_directory: ~/jsondiff
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup Build Variables
          command: |
            echo 'export VERSION=${CIRCLE_TAG:1}' >> $BASH_ENV
            echo 'export BUILD_DATE=`date -u +'%Y-%m-%dT%H:%M:%SZ'`' >> $BASH_ENV
      - run:
          name: Run and test jsondiff
          command: |
            ./build.sh $VERSION
            docker inspect polyglotted/jsondiff:$VERSION
      - deploy:
          name: DockerHub Deploy
          command: |
            echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
            docker push polyglotted/jsondiff:$VERSION

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+).*/
            branches:
              ignore: /.*/